language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1024m"
 - chmod +x gradlew
script:
 - ./gradlew check
 - ./gradlew codeCoverageReport
after_success:
 - bash <(curl -s https://codecov.io/bash)